//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Interfaces.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TransString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TransString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shop.Interfaces.Resources.TransString", typeof(TransString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pueden modificar los permisos del administrador del grupo.
        /// </summary>
        public static string AdminGrupoNoModificable {
            get {
                return ResourceManager.GetString("AdminGrupoNoModificable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El content con id={0} no forma parte de su subscripción..
        /// </summary>
        public static string ContentNoFormaParteSubscripcion {
            get {
                return ResourceManager.GetString("ContentNoFormaParteSubscripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe el elemento en la base de datos.
        /// </summary>
        public static string ElementoNoEncontrado {
            get {
                return ResourceManager.GetString("ElementoNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error mientras se accedía a los datos. Consulte un Administrador.
        /// </summary>
        public static string ErrorBaseDatos {
            get {
                return ResourceManager.GetString("ErrorBaseDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El producto ya existe en la tienda.
        /// </summary>
        public static string ExisteProductoEnTienda {
            get {
                return ResourceManager.GetString("ExisteProductoEnTienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe el grupo en la base de datos.
        /// </summary>
        public static string GrupoNoEncontrado {
            get {
                return ResourceManager.GetString("GrupoNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El grupo no puede aceptar order details de ese content.
        /// </summary>
        public static string GrupoNoPuedeAceptarOrderDetails {
            get {
                return ResourceManager.GetString("GrupoNoPuedeAceptarOrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay ajustes de configuración para enviar correos electrónicos.
        /// </summary>
        public static string NoAjustesParaEnviarCorreos {
            get {
                return ResourceManager.GetString("NoAjustesParaEnviarCorreos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo actualizar la contraseña.
        /// </summary>
        public static string NoSePudoActualizarLaContraseña {
            get {
                return ResourceManager.GetString("NoSePudoActualizarLaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo reiniciar la contraseña.
        /// </summary>
        public static string NoSePudoReiniciarLaContraseña {
            get {
                return ResourceManager.GetString("NoSePudoReiniciarLaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted no es el creador del grupo.
        /// </summary>
        public static string NotGroupAdmin {
            get {
                return ResourceManager.GetString("NotGroupAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe el estado de subscripción que desea configurar.
        /// </summary>
        public static string NotValidGroupOrderSubscriptionStatus {
            get {
                return ResourceManager.GetString("NotValidGroupOrderSubscriptionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación completada satisfactoriamente.
        /// </summary>
        public static string OperacionCompletada {
            get {
                return ResourceManager.GetString("OperacionCompletada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetro no encontrado.
        /// </summary>
        public static string ParametroNoEncontrado {
            get {
                return ResourceManager.GetString("ParametroNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parámetro con id={0} no pertenece al content con id={1}.
        /// </summary>
        public static string ParametroNoPerteneceAlContent {
            get {
                return ResourceManager.GetString("ParametroNoPerteneceAlContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para este content ya existe un parámetro con el mismo tipo y nombre..
        /// </summary>
        public static string ParametroYaExiste {
            get {
                return ResourceManager.GetString("ParametroYaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El producto no fue encontrado.
        /// </summary>
        public static string ProductoNoEncontrado {
            get {
                return ResourceManager.GetString("ProductoNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe uno o más productos que no pertencen a la tienda.
        /// </summary>
        public static string ProductoNoRegistradoEnTienda {
            get {
                return ResourceManager.GetString("ProductoNoRegistradoEnTienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol asociado a usuarios.
        /// </summary>
        public static string RoleAsociadoAUsuarios {
            get {
                return ResourceManager.GetString("RoleAsociadoAUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol no válido.
        /// </summary>
        public static string RoleNoValido {
            get {
                return ResourceManager.GetString("RoleNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario que intenta subscribir ya esta subscrito al grupo.
        /// </summary>
        public static string UserAlreadySubscribed {
            get {
                return ResourceManager.GetString("UserAlreadySubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La subscripcion del usuario no le permite crear tantas order details como Contents tiene el grupo.
        /// </summary>
        public static string UserCantHaveMoreOrders {
            get {
                return ResourceManager.GetString("UserCantHaveMoreOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El grupo tiene Contents que no figuran en la Subscripcion del Usuario.
        /// </summary>
        public static string UserCantSubscribeToAllGroupCommanders {
            get {
                return ResourceManager.GetString("UserCantSubscribeToAllGroupCommanders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no encontrado.
        /// </summary>
        public static string UsuarioNoEncontrado {
            get {
                return ResourceManager.GetString("UsuarioNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario o contraseña incorrecto.
        /// </summary>
        public static string UsuarioOContraseñaIncorrecto {
            get {
                return ResourceManager.GetString("UsuarioOContraseñaIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede configurar acceso a usuario sin OrderDetails en el grupo.
        /// </summary>
        public static string UsuarioSinOrderDetailsEnGrupo {
            get {
                return ResourceManager.GetString("UsuarioSinOrderDetailsEnGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted no tiene permisos para subscribir al usuario.
        /// </summary>
        public static string YouDontHavePermissionToSubscribeUser {
            get {
                return ResourceManager.GetString("YouDontHavePermissionToSubscribeUser", resourceCulture);
            }
        }
    }
}
